package ifsp.vitaesangue.model;

public enum ResourcesAllow {
	USUARIO, 
	BOLSA_REQUISICAO,
	BOLSA_ENTREGA,
	CONTRATO,
	BOLSA_DESCARTE,
	ESTABELECIMENTO, 
	HEMOCENTRO,
	HISTORICO, 
	HOSPITAL, 
	PERFIL, 
	SOLICITACAO_ACESSO,
	BOLSA_UTILIZACAO
}
